### ISSUE TITLE
No animation after player enters a house

### ISSUE THREAD

**Issue by Damjandeveloper133** [Gdevelop-game/GDevelop-Open-Game#37]
I come near any house  then i press a and then enter and the animation that gets in the house dosen't play and then the fading effect  happens but it results a black screen

**Comment by the-gem-dev** [comment]
could you share a video on this please

**Comment by PawBud** [comment]
This happens to me to, I thought that we have progressed only so far? (Sorry I didn’t really open the game too often so I am unaware of every detail )

**Comment by the-gem-dev** [comment]
I would work on that soon

**Comment by the-gem-dev** [comment]
it should be fixed by now

**Comment by PawBud** [comment]
https://streamable.com/bbwd6h I think it still persists? 

GDevelop version:- Beta-89.00
OS:- Linux 20.04 LTS

**Comment by PawBud** [comment]
Sorry if I am doing something wrong, in that case, you may close this issue :)

**Comment by the-gem-dev** [comment]
can you share a video about this

**Comment by PawBud** [comment]
Just to rectify, This is not a bug according to @the-gem-dev and the video is https://streamable.com/bbwd6h

**Comment by the-gem-dev** [comment]
Once the game is done our player won't be able to preview the rooms scene without entering a door in the overworked scene
